#!/bin/sh

case $1 in
        start)
        if pidof wpa_supplicant > /dev/null; then
            echo "wpa_supplicant already running, skipping..."
        else
            echo "Starting wpa_supplicant..."
            wpa_supplicant -B -i wlan0 -c /etc/wpa_supplicant.conf
            udhcpc -i wlan0
        fi
                ;;
        stop)
                ;;
        *)
                exit 1
                ;;
esac